// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.9.0
// source: api/proto/v1/nba_service.proto

package nba_v

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NBAService_CreatePlayer_FullMethodName     = "/v1.NBAService/CreatePlayer"
	NBAService_GetPlayer_FullMethodName        = "/v1.NBAService/GetPlayer"
	NBAService_UpdatePlayer_FullMethodName     = "/v1.NBAService/UpdatePlayer"
	NBAService_DeletePlayer_FullMethodName     = "/v1.NBAService/DeletePlayer"
	NBAService_ListPlayers_FullMethodName      = "/v1.NBAService/ListPlayers"
	NBAService_GetPlayersByTeam_FullMethodName = "/v1.NBAService/GetPlayersByTeam"
)

// NBAServiceClient is the client API for NBAService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NBA球员管理服务
type NBAServiceClient interface {
	// 创建球员
	CreatePlayer(ctx context.Context, in *CreatePlayerRequest, opts ...grpc.CallOption) (*PlayerResponse, error)
	// 获取球员详情
	GetPlayer(ctx context.Context, in *GetPlayerRequest, opts ...grpc.CallOption) (*PlayerResponse, error)
	// 更新球员信息
	UpdatePlayer(ctx context.Context, in *UpdatePlayerRequest, opts ...grpc.CallOption) (*PlayerResponse, error)
	// 删除球员
	DeletePlayer(ctx context.Context, in *DeletePlayerRequest, opts ...grpc.CallOption) (*DeletePlayerResponse, error)
	// 按条件查询球员列表
	ListPlayers(ctx context.Context, in *ListPlayersRequest, opts ...grpc.CallOption) (*ListPlayersResponse, error)
	// 按球队ID获取球员
	GetPlayersByTeam(ctx context.Context, in *GetPlayersByTeamRequest, opts ...grpc.CallOption) (*ListPlayersResponse, error)
}

type nBAServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNBAServiceClient(cc grpc.ClientConnInterface) NBAServiceClient {
	return &nBAServiceClient{cc}
}

func (c *nBAServiceClient) CreatePlayer(ctx context.Context, in *CreatePlayerRequest, opts ...grpc.CallOption) (*PlayerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerResponse)
	err := c.cc.Invoke(ctx, NBAService_CreatePlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nBAServiceClient) GetPlayer(ctx context.Context, in *GetPlayerRequest, opts ...grpc.CallOption) (*PlayerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerResponse)
	err := c.cc.Invoke(ctx, NBAService_GetPlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nBAServiceClient) UpdatePlayer(ctx context.Context, in *UpdatePlayerRequest, opts ...grpc.CallOption) (*PlayerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerResponse)
	err := c.cc.Invoke(ctx, NBAService_UpdatePlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nBAServiceClient) DeletePlayer(ctx context.Context, in *DeletePlayerRequest, opts ...grpc.CallOption) (*DeletePlayerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePlayerResponse)
	err := c.cc.Invoke(ctx, NBAService_DeletePlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nBAServiceClient) ListPlayers(ctx context.Context, in *ListPlayersRequest, opts ...grpc.CallOption) (*ListPlayersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPlayersResponse)
	err := c.cc.Invoke(ctx, NBAService_ListPlayers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nBAServiceClient) GetPlayersByTeam(ctx context.Context, in *GetPlayersByTeamRequest, opts ...grpc.CallOption) (*ListPlayersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPlayersResponse)
	err := c.cc.Invoke(ctx, NBAService_GetPlayersByTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NBAServiceServer is the server API for NBAService service.
// All implementations must embed UnimplementedNBAServiceServer
// for forward compatibility.
//
// NBA球员管理服务
type NBAServiceServer interface {
	// 创建球员
	CreatePlayer(context.Context, *CreatePlayerRequest) (*PlayerResponse, error)
	// 获取球员详情
	GetPlayer(context.Context, *GetPlayerRequest) (*PlayerResponse, error)
	// 更新球员信息
	UpdatePlayer(context.Context, *UpdatePlayerRequest) (*PlayerResponse, error)
	// 删除球员
	DeletePlayer(context.Context, *DeletePlayerRequest) (*DeletePlayerResponse, error)
	// 按条件查询球员列表
	ListPlayers(context.Context, *ListPlayersRequest) (*ListPlayersResponse, error)
	// 按球队ID获取球员
	GetPlayersByTeam(context.Context, *GetPlayersByTeamRequest) (*ListPlayersResponse, error)
	mustEmbedUnimplementedNBAServiceServer()
}

// UnimplementedNBAServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNBAServiceServer struct{}

func (UnimplementedNBAServiceServer) CreatePlayer(context.Context, *CreatePlayerRequest) (*PlayerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePlayer not implemented")
}
func (UnimplementedNBAServiceServer) GetPlayer(context.Context, *GetPlayerRequest) (*PlayerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlayer not implemented")
}
func (UnimplementedNBAServiceServer) UpdatePlayer(context.Context, *UpdatePlayerRequest) (*PlayerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePlayer not implemented")
}
func (UnimplementedNBAServiceServer) DeletePlayer(context.Context, *DeletePlayerRequest) (*DeletePlayerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePlayer not implemented")
}
func (UnimplementedNBAServiceServer) ListPlayers(context.Context, *ListPlayersRequest) (*ListPlayersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlayers not implemented")
}
func (UnimplementedNBAServiceServer) GetPlayersByTeam(context.Context, *GetPlayersByTeamRequest) (*ListPlayersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlayersByTeam not implemented")
}
func (UnimplementedNBAServiceServer) mustEmbedUnimplementedNBAServiceServer() {}
func (UnimplementedNBAServiceServer) testEmbeddedByValue()                    {}

// UnsafeNBAServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NBAServiceServer will
// result in compilation errors.
type UnsafeNBAServiceServer interface {
	mustEmbedUnimplementedNBAServiceServer()
}

func RegisterNBAServiceServer(s grpc.ServiceRegistrar, srv NBAServiceServer) {
	// If the following call panics, it indicates UnimplementedNBAServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NBAService_ServiceDesc, srv)
}

func _NBAService_CreatePlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NBAServiceServer).CreatePlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NBAService_CreatePlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NBAServiceServer).CreatePlayer(ctx, req.(*CreatePlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NBAService_GetPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NBAServiceServer).GetPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NBAService_GetPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NBAServiceServer).GetPlayer(ctx, req.(*GetPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NBAService_UpdatePlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NBAServiceServer).UpdatePlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NBAService_UpdatePlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NBAServiceServer).UpdatePlayer(ctx, req.(*UpdatePlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NBAService_DeletePlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NBAServiceServer).DeletePlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NBAService_DeletePlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NBAServiceServer).DeletePlayer(ctx, req.(*DeletePlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NBAService_ListPlayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPlayersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NBAServiceServer).ListPlayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NBAService_ListPlayers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NBAServiceServer).ListPlayers(ctx, req.(*ListPlayersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NBAService_GetPlayersByTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayersByTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NBAServiceServer).GetPlayersByTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NBAService_GetPlayersByTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NBAServiceServer).GetPlayersByTeam(ctx, req.(*GetPlayersByTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NBAService_ServiceDesc is the grpc.ServiceDesc for NBAService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NBAService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.NBAService",
	HandlerType: (*NBAServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePlayer",
			Handler:    _NBAService_CreatePlayer_Handler,
		},
		{
			MethodName: "GetPlayer",
			Handler:    _NBAService_GetPlayer_Handler,
		},
		{
			MethodName: "UpdatePlayer",
			Handler:    _NBAService_UpdatePlayer_Handler,
		},
		{
			MethodName: "DeletePlayer",
			Handler:    _NBAService_DeletePlayer_Handler,
		},
		{
			MethodName: "ListPlayers",
			Handler:    _NBAService_ListPlayers_Handler,
		},
		{
			MethodName: "GetPlayersByTeam",
			Handler:    _NBAService_GetPlayersByTeam_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1/nba_service.proto",
}
