// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.9.0
// source: api/proto/v1/nba_service.proto

package nba_v

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 球员位置枚举
type Position int32

const (
	Position_POSITION_UNKNOWN Position = 0
	Position_PG               Position = 1 // 控球后卫
	Position_SG               Position = 2 // 得分后卫
	Position_SF               Position = 3 // 小前锋
	Position_PF               Position = 4 // 大前锋
	Position_C                Position = 5 // 中锋
)

// Enum value maps for Position.
var (
	Position_name = map[int32]string{
		0: "POSITION_UNKNOWN",
		1: "PG",
		2: "SG",
		3: "SF",
		4: "PF",
		5: "C",
	}
	Position_value = map[string]int32{
		"POSITION_UNKNOWN": 0,
		"PG":               1,
		"SG":               2,
		"SF":               3,
		"PF":               4,
		"C":                5,
	}
)

func (x Position) Enum() *Position {
	p := new(Position)
	*p = x
	return p
}

func (x Position) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Position) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_nba_service_proto_enumTypes[0].Descriptor()
}

func (Position) Type() protoreflect.EnumType {
	return &file_api_proto_v1_nba_service_proto_enumTypes[0]
}

func (x Position) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Position.Descriptor instead.
func (Position) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_nba_service_proto_rawDescGZIP(), []int{0}
}

// 球员状态枚举
type PlayerStatus int32

const (
	PlayerStatus_STATUS_UNKNOWN PlayerStatus = 0
	PlayerStatus_RETIRED        PlayerStatus = 1 // 退役
	PlayerStatus_ACTIVE         PlayerStatus = 2 // 现役
	PlayerStatus_INJURED        PlayerStatus = 3 // 受伤
	PlayerStatus_ASSIGNED       PlayerStatus = 4 // 下放
)

// Enum value maps for PlayerStatus.
var (
	PlayerStatus_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "RETIRED",
		2: "ACTIVE",
		3: "INJURED",
		4: "ASSIGNED",
	}
	PlayerStatus_value = map[string]int32{
		"STATUS_UNKNOWN": 0,
		"RETIRED":        1,
		"ACTIVE":         2,
		"INJURED":        3,
		"ASSIGNED":       4,
	}
)

func (x PlayerStatus) Enum() *PlayerStatus {
	p := new(PlayerStatus)
	*p = x
	return p
}

func (x PlayerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_nba_service_proto_enumTypes[1].Descriptor()
}

func (PlayerStatus) Type() protoreflect.EnumType {
	return &file_api_proto_v1_nba_service_proto_enumTypes[1]
}

func (x PlayerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerStatus.Descriptor instead.
func (PlayerStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_nba_service_proto_rawDescGZIP(), []int{1}
}

// 创建球员请求
type CreatePlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                      // 球员姓名
	TeamId        int32                  `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`                   // 所属球队ID
	JerseyNumber  int32                  `protobuf:"varint,3,opt,name=jersey_number,json=jerseyNumber,proto3" json:"jersey_number,omitempty"` // 球衣号码 (1-99)
	Position      Position               `protobuf:"varint,4,opt,name=position,proto3,enum=v1.Position" json:"position,omitempty"`            // 位置
	Height        float64                `protobuf:"fixed64,5,opt,name=height,proto3" json:"height,omitempty"`                                // 身高 (米), 例如: 1.98
	Weight        float64                `protobuf:"fixed64,6,opt,name=weight,proto3" json:"weight,omitempty"`                                // 体重 (kg), 例如: 95.5
	Birthday      string                 `protobuf:"bytes,7,opt,name=birthday,proto3" json:"birthday,omitempty"`                              // 出生日期, 格式: YYYY-MM-DD
	Status        PlayerStatus           `protobuf:"varint,8,opt,name=status,proto3,enum=v1.PlayerStatus" json:"status,omitempty"`            // 状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlayerRequest) Reset() {
	*x = CreatePlayerRequest{}
	mi := &file_api_proto_v1_nba_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayerRequest) ProtoMessage() {}

func (x *CreatePlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_nba_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayerRequest.ProtoReflect.Descriptor instead.
func (*CreatePlayerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_nba_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePlayerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePlayerRequest) GetTeamId() int32 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *CreatePlayerRequest) GetJerseyNumber() int32 {
	if x != nil {
		return x.JerseyNumber
	}
	return 0
}

func (x *CreatePlayerRequest) GetPosition() Position {
	if x != nil {
		return x.Position
	}
	return Position_POSITION_UNKNOWN
}

func (x *CreatePlayerRequest) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CreatePlayerRequest) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *CreatePlayerRequest) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *CreatePlayerRequest) GetStatus() PlayerStatus {
	if x != nil {
		return x.Status
	}
	return PlayerStatus_STATUS_UNKNOWN
}

// 获取球员请求
type GetPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 球员ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerRequest) Reset() {
	*x = GetPlayerRequest{}
	mi := &file_api_proto_v1_nba_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerRequest) ProtoMessage() {}

func (x *GetPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_nba_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_nba_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetPlayerRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 更新球员请求
type UpdatePlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                         // 球员ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                      // 球员姓名
	TeamId        int32                  `protobuf:"varint,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`                   // 所属球队ID
	JerseyNumber  int32                  `protobuf:"varint,4,opt,name=jersey_number,json=jerseyNumber,proto3" json:"jersey_number,omitempty"` // 球衣号码
	Position      Position               `protobuf:"varint,5,opt,name=position,proto3,enum=v1.Position" json:"position,omitempty"`            // 位置
	Height        float64                `protobuf:"fixed64,6,opt,name=height,proto3" json:"height,omitempty"`                                // 身高
	Weight        float64                `protobuf:"fixed64,7,opt,name=weight,proto3" json:"weight,omitempty"`                                // 体重
	Birthday      string                 `protobuf:"bytes,8,opt,name=birthday,proto3" json:"birthday,omitempty"`                              // 出生日期
	Status        PlayerStatus           `protobuf:"varint,9,opt,name=status,proto3,enum=v1.PlayerStatus" json:"status,omitempty"`            // 状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlayerRequest) Reset() {
	*x = UpdatePlayerRequest{}
	mi := &file_api_proto_v1_nba_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlayerRequest) ProtoMessage() {}

func (x *UpdatePlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_nba_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlayerRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlayerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_nba_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdatePlayerRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePlayerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePlayerRequest) GetTeamId() int32 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *UpdatePlayerRequest) GetJerseyNumber() int32 {
	if x != nil {
		return x.JerseyNumber
	}
	return 0
}

func (x *UpdatePlayerRequest) GetPosition() Position {
	if x != nil {
		return x.Position
	}
	return Position_POSITION_UNKNOWN
}

func (x *UpdatePlayerRequest) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *UpdatePlayerRequest) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *UpdatePlayerRequest) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *UpdatePlayerRequest) GetStatus() PlayerStatus {
	if x != nil {
		return x.Status
	}
	return PlayerStatus_STATUS_UNKNOWN
}

// 删除球员请求
type DeletePlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 球员ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePlayerRequest) Reset() {
	*x = DeletePlayerRequest{}
	mi := &file_api_proto_v1_nba_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlayerRequest) ProtoMessage() {}

func (x *DeletePlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_nba_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlayerRequest.ProtoReflect.Descriptor instead.
func (*DeletePlayerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_nba_service_proto_rawDescGZIP(), []int{3}
}

func (x *DeletePlayerRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 删除球员响应
type DeletePlayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePlayerResponse) Reset() {
	*x = DeletePlayerResponse{}
	mi := &file_api_proto_v1_nba_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlayerResponse) ProtoMessage() {}

func (x *DeletePlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_nba_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlayerResponse.ProtoReflect.Descriptor instead.
func (*DeletePlayerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_nba_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeletePlayerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeletePlayerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 球员响应（完整信息）
type PlayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                         // 球员ID
	TeamId        int32                  `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`                   // 所属球队ID
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                      // 球员姓名
	JerseyNumber  int32                  `protobuf:"varint,4,opt,name=jersey_number,json=jerseyNumber,proto3" json:"jersey_number,omitempty"` // 球衣号码
	Position      Position               `protobuf:"varint,5,opt,name=position,proto3,enum=v1.Position" json:"position,omitempty"`            // 位置
	Height        float64                `protobuf:"fixed64,6,opt,name=height,proto3" json:"height,omitempty"`                                // 身高 (米)
	Weight        float64                `protobuf:"fixed64,7,opt,name=weight,proto3" json:"weight,omitempty"`                                // 体重 (kg)
	Birthday      string                 `protobuf:"bytes,8,opt,name=birthday,proto3" json:"birthday,omitempty"`                              // 出生日期
	Status        PlayerStatus           `protobuf:"varint,9,opt,name=status,proto3,enum=v1.PlayerStatus" json:"status,omitempty"`            // 状态
	StatusText    string                 `protobuf:"bytes,10,opt,name=status_text,json=statusText,proto3" json:"status_text,omitempty"`       // 状态文本
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`          // 创建时间
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`          // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerResponse) Reset() {
	*x = PlayerResponse{}
	mi := &file_api_proto_v1_nba_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerResponse) ProtoMessage() {}

func (x *PlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_nba_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerResponse.ProtoReflect.Descriptor instead.
func (*PlayerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_nba_service_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlayerResponse) GetTeamId() int32 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *PlayerResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerResponse) GetJerseyNumber() int32 {
	if x != nil {
		return x.JerseyNumber
	}
	return 0
}

func (x *PlayerResponse) GetPosition() Position {
	if x != nil {
		return x.Position
	}
	return Position_POSITION_UNKNOWN
}

func (x *PlayerResponse) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *PlayerResponse) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *PlayerResponse) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *PlayerResponse) GetStatus() PlayerStatus {
	if x != nil {
		return x.Status
	}
	return PlayerStatus_STATUS_UNKNOWN
}

func (x *PlayerResponse) GetStatusText() string {
	if x != nil {
		return x.StatusText
	}
	return ""
}

func (x *PlayerResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PlayerResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 查询球员列表请求
type ListPlayersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                          // 页码，从1开始
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`  // 每页数量，默认20
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                           // 按姓名模糊查询
	TeamId        int32                  `protobuf:"varint,4,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`        // 按球队ID查询
	Position      Position               `protobuf:"varint,5,opt,name=position,proto3,enum=v1.Position" json:"position,omitempty"` // 按位置查询
	Status        PlayerStatus           `protobuf:"varint,6,opt,name=status,proto3,enum=v1.PlayerStatus" json:"status,omitempty"` // 按状态查询
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlayersRequest) Reset() {
	*x = ListPlayersRequest{}
	mi := &file_api_proto_v1_nba_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlayersRequest) ProtoMessage() {}

func (x *ListPlayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_nba_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlayersRequest.ProtoReflect.Descriptor instead.
func (*ListPlayersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_nba_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListPlayersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPlayersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPlayersRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListPlayersRequest) GetTeamId() int32 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *ListPlayersRequest) GetPosition() Position {
	if x != nil {
		return x.Position
	}
	return Position_POSITION_UNKNOWN
}

func (x *ListPlayersRequest) GetStatus() PlayerStatus {
	if x != nil {
		return x.Status
	}
	return PlayerStatus_STATUS_UNKNOWN
}

// 球员列表响应
type ListPlayersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*PlayerResponse      `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`                    // 球员列表
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`                       // 总数量
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                         // 当前页码
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlayersResponse) Reset() {
	*x = ListPlayersResponse{}
	mi := &file_api_proto_v1_nba_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlayersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlayersResponse) ProtoMessage() {}

func (x *ListPlayersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_nba_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlayersResponse.ProtoReflect.Descriptor instead.
func (*ListPlayersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_nba_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListPlayersResponse) GetPlayers() []*PlayerResponse {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *ListPlayersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListPlayersResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPlayersResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 按球队获取球员请求
type GetPlayersByTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int32                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"` // 球队ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayersByTeamRequest) Reset() {
	*x = GetPlayersByTeamRequest{}
	mi := &file_api_proto_v1_nba_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayersByTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayersByTeamRequest) ProtoMessage() {}

func (x *GetPlayersByTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_nba_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayersByTeamRequest.ProtoReflect.Descriptor instead.
func (*GetPlayersByTeamRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_nba_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetPlayersByTeamRequest) GetTeamId() int32 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

var File_api_proto_v1_nba_service_proto protoreflect.FileDescriptor

const file_api_proto_v1_nba_service_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/v1/nba_service.proto\x12\x02v1\"\x87\x02\n" +
	"\x13CreatePlayerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\x05R\x06teamId\x12#\n" +
	"\rjersey_number\x18\x03 \x01(\x05R\fjerseyNumber\x12(\n" +
	"\bposition\x18\x04 \x01(\x0e2\f.v1.PositionR\bposition\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x01R\x06height\x12\x16\n" +
	"\x06weight\x18\x06 \x01(\x01R\x06weight\x12\x1a\n" +
	"\bbirthday\x18\a \x01(\tR\bbirthday\x12(\n" +
	"\x06status\x18\b \x01(\x0e2\x10.v1.PlayerStatusR\x06status\"\"\n" +
	"\x10GetPlayerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x97\x02\n" +
	"\x13UpdatePlayerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\ateam_id\x18\x03 \x01(\x05R\x06teamId\x12#\n" +
	"\rjersey_number\x18\x04 \x01(\x05R\fjerseyNumber\x12(\n" +
	"\bposition\x18\x05 \x01(\x0e2\f.v1.PositionR\bposition\x12\x16\n" +
	"\x06height\x18\x06 \x01(\x01R\x06height\x12\x16\n" +
	"\x06weight\x18\a \x01(\x01R\x06weight\x12\x1a\n" +
	"\bbirthday\x18\b \x01(\tR\bbirthday\x12(\n" +
	"\x06status\x18\t \x01(\x0e2\x10.v1.PlayerStatusR\x06status\"%\n" +
	"\x13DeletePlayerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"J\n" +
	"\x14DeletePlayerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xf1\x02\n" +
	"\x0ePlayerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\x05R\x06teamId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12#\n" +
	"\rjersey_number\x18\x04 \x01(\x05R\fjerseyNumber\x12(\n" +
	"\bposition\x18\x05 \x01(\x0e2\f.v1.PositionR\bposition\x12\x16\n" +
	"\x06height\x18\x06 \x01(\x01R\x06height\x12\x16\n" +
	"\x06weight\x18\a \x01(\x01R\x06weight\x12\x1a\n" +
	"\bbirthday\x18\b \x01(\tR\bbirthday\x12(\n" +
	"\x06status\x18\t \x01(\x0e2\x10.v1.PlayerStatusR\x06status\x12\x1f\n" +
	"\vstatus_text\x18\n" +
	" \x01(\tR\n" +
	"statusText\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\"\xc6\x01\n" +
	"\x12ListPlayersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x17\n" +
	"\ateam_id\x18\x04 \x01(\x05R\x06teamId\x12(\n" +
	"\bposition\x18\x05 \x01(\x0e2\f.v1.PositionR\bposition\x12(\n" +
	"\x06status\x18\x06 \x01(\x0e2\x10.v1.PlayerStatusR\x06status\"\x8a\x01\n" +
	"\x13ListPlayersResponse\x12,\n" +
	"\aplayers\x18\x01 \x03(\v2\x12.v1.PlayerResponseR\aplayers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"2\n" +
	"\x17GetPlayersByTeamRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x05R\x06teamId*G\n" +
	"\bPosition\x12\x14\n" +
	"\x10POSITION_UNKNOWN\x10\x00\x12\x06\n" +
	"\x02PG\x10\x01\x12\x06\n" +
	"\x02SG\x10\x02\x12\x06\n" +
	"\x02SF\x10\x03\x12\x06\n" +
	"\x02PF\x10\x04\x12\x05\n" +
	"\x01C\x10\x05*V\n" +
	"\fPlayerStatus\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\v\n" +
	"\aRETIRED\x10\x01\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x02\x12\v\n" +
	"\aINJURED\x10\x03\x12\f\n" +
	"\bASSIGNED\x10\x042\x8a\x03\n" +
	"\n" +
	"NBAService\x12;\n" +
	"\fCreatePlayer\x12\x17.v1.CreatePlayerRequest\x1a\x12.v1.PlayerResponse\x125\n" +
	"\tGetPlayer\x12\x14.v1.GetPlayerRequest\x1a\x12.v1.PlayerResponse\x12;\n" +
	"\fUpdatePlayer\x12\x17.v1.UpdatePlayerRequest\x1a\x12.v1.PlayerResponse\x12A\n" +
	"\fDeletePlayer\x12\x17.v1.DeletePlayerRequest\x1a\x18.v1.DeletePlayerResponse\x12>\n" +
	"\vListPlayers\x12\x16.v1.ListPlayersRequest\x1a\x17.v1.ListPlayersResponse\x12H\n" +
	"\x10GetPlayersByTeam\x12\x1b.v1.GetPlayersByTeamRequest\x1a\x17.v1.ListPlayersResponseB Z\x1enba_service/api/proto/v1;nba_vb\x06proto3"

var (
	file_api_proto_v1_nba_service_proto_rawDescOnce sync.Once
	file_api_proto_v1_nba_service_proto_rawDescData []byte
)

func file_api_proto_v1_nba_service_proto_rawDescGZIP() []byte {
	file_api_proto_v1_nba_service_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_nba_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_nba_service_proto_rawDesc), len(file_api_proto_v1_nba_service_proto_rawDesc)))
	})
	return file_api_proto_v1_nba_service_proto_rawDescData
}

var file_api_proto_v1_nba_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_v1_nba_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_proto_v1_nba_service_proto_goTypes = []any{
	(Position)(0),                   // 0: v1.Position
	(PlayerStatus)(0),               // 1: v1.PlayerStatus
	(*CreatePlayerRequest)(nil),     // 2: v1.CreatePlayerRequest
	(*GetPlayerRequest)(nil),        // 3: v1.GetPlayerRequest
	(*UpdatePlayerRequest)(nil),     // 4: v1.UpdatePlayerRequest
	(*DeletePlayerRequest)(nil),     // 5: v1.DeletePlayerRequest
	(*DeletePlayerResponse)(nil),    // 6: v1.DeletePlayerResponse
	(*PlayerResponse)(nil),          // 7: v1.PlayerResponse
	(*ListPlayersRequest)(nil),      // 8: v1.ListPlayersRequest
	(*ListPlayersResponse)(nil),     // 9: v1.ListPlayersResponse
	(*GetPlayersByTeamRequest)(nil), // 10: v1.GetPlayersByTeamRequest
}
var file_api_proto_v1_nba_service_proto_depIdxs = []int32{
	0,  // 0: v1.CreatePlayerRequest.position:type_name -> v1.Position
	1,  // 1: v1.CreatePlayerRequest.status:type_name -> v1.PlayerStatus
	0,  // 2: v1.UpdatePlayerRequest.position:type_name -> v1.Position
	1,  // 3: v1.UpdatePlayerRequest.status:type_name -> v1.PlayerStatus
	0,  // 4: v1.PlayerResponse.position:type_name -> v1.Position
	1,  // 5: v1.PlayerResponse.status:type_name -> v1.PlayerStatus
	0,  // 6: v1.ListPlayersRequest.position:type_name -> v1.Position
	1,  // 7: v1.ListPlayersRequest.status:type_name -> v1.PlayerStatus
	7,  // 8: v1.ListPlayersResponse.players:type_name -> v1.PlayerResponse
	2,  // 9: v1.NBAService.CreatePlayer:input_type -> v1.CreatePlayerRequest
	3,  // 10: v1.NBAService.GetPlayer:input_type -> v1.GetPlayerRequest
	4,  // 11: v1.NBAService.UpdatePlayer:input_type -> v1.UpdatePlayerRequest
	5,  // 12: v1.NBAService.DeletePlayer:input_type -> v1.DeletePlayerRequest
	8,  // 13: v1.NBAService.ListPlayers:input_type -> v1.ListPlayersRequest
	10, // 14: v1.NBAService.GetPlayersByTeam:input_type -> v1.GetPlayersByTeamRequest
	7,  // 15: v1.NBAService.CreatePlayer:output_type -> v1.PlayerResponse
	7,  // 16: v1.NBAService.GetPlayer:output_type -> v1.PlayerResponse
	7,  // 17: v1.NBAService.UpdatePlayer:output_type -> v1.PlayerResponse
	6,  // 18: v1.NBAService.DeletePlayer:output_type -> v1.DeletePlayerResponse
	9,  // 19: v1.NBAService.ListPlayers:output_type -> v1.ListPlayersResponse
	9,  // 20: v1.NBAService.GetPlayersByTeam:output_type -> v1.ListPlayersResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_proto_v1_nba_service_proto_init() }
func file_api_proto_v1_nba_service_proto_init() {
	if File_api_proto_v1_nba_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_nba_service_proto_rawDesc), len(file_api_proto_v1_nba_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_nba_service_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_nba_service_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_nba_service_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_nba_service_proto_msgTypes,
	}.Build()
	File_api_proto_v1_nba_service_proto = out.File
	file_api_proto_v1_nba_service_proto_goTypes = nil
	file_api_proto_v1_nba_service_proto_depIdxs = nil
}
